logging:
  level:
    root: WARN
    es.upm.api: INFO

app:
  hosting: render

spring:
  jpa:
    hibernate:
      ddl-auto: update
  # Valores creados en Render → Databases → Database → Connect
  # actualizado
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}