server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres-server:5432/iwvgdevopsdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true