logging:
  level:
    root: WARN
    es.upm.api: INFO

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

app:
  hosting: AWS

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/iwvgdevopsdb
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}