name: CD POSTGRES
on:
  push:
    branches:
      - master

jobs:
  cd:
    name: Deploy Docker Postgres on AWS Lightsail
    runs-on: ubuntu-22.04

    steps:
      - name: 🚀 Deploy on AWS Lightsail
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.AWS_LIGHTSAIL_IP_MAIN }}
          username: ${{ secrets.AWS_LIGHTSAIL_USER_MAIN }}
          key: ${{ secrets.AWS_LIGHTSAIL_SSH_KEY_MAIN }}
          script: |
            sudo docker rm -f postgres || true
            sudo docker network create devops || true
            sudo docker run -d \
              --name postgres \
              --restart always \
              --network devops \
              -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
              -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
              -e POSTGRES_DB=iwvgdevopsdb \
              postgres:15.10