name: CD
on:
  push:
    branches:
      - master

jobs:
  cd:
    name: Build & Push GitHub Package & Deploy on Render Docker Image
    runs-on: ubuntu-22.04

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ☕ Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: 🏷️ Prepare container image metadata (repository in lowercase, artifact, version...)
        run: |
          echo "REPOSITORY=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
          echo "ARTIFACT=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV
          echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      # 1º Crear Token de Acceso Personal:
      #    GitHub → Settings → Developer settings → Personal access tokens → Generate new token (classic)
      #    Permisos mínimos: write:packages, read:packages, delete:packages, repo
      #
      # 2º Crear secret en GitHub:
      #    Repo → Settings → Secrets and variables → Actions → New repository secret
      #    Name: GHCR_PERSONAL_ACCESS_TOKEN, Value: <tu token>
      - name: 📦 Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PERSONAL_ACCESS_TOKEN }}

      - name: 🐳 Build & Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          secrets: github_token=${{ secrets.GITHUB_TOKEN }}
          tags: |
            ghcr.io/${{ env.REPOSITORY }}:${{ env.VERSION }}
            ghcr.io/${{ env.REPOSITORY }}:latest