name: CI
on:
  push:
    branches: [develop,feature-*,master]

jobs:
  devops:
    name: Tests & CodeQL & SonarCloud
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      actions: read
      security-events: write

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ☕ Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: 🏷️ Extract artifact from pom
        run: echo "ARTIFACT=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV

      - name: 🛡️ Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java
          queries: security-extended

      - name: ✅ Run Unit & Integration Test & Functional Test
        run: mvn -B verify

      - name: Notificar éxito a Slack
        if: success() # Solo se dispara si la compilación y tests fueron exitosos
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "✅ *¡Integración Continua Exitosa!*\n*Repositorio:* ${{ github.repository }}\n*Rama:* ${{ github.ref_name }}\n*Autor:* ${{ github.actor }}\n*Commit:* ${{ github.sha }}\n*Estado:* La API Spring Boot ha sido compilada y validada correctamente con las pruebas de Maven."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notificar fallo a Slack
        if: failure() # Solo se dispara si falló algún paso anterior
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "🚨 *¡Fallo en la Integración Continua!*\n*Repositorio:* ${{ github.repository }}\n*Rama:* ${{ github.ref_name }}\n*Autor:* ${{ github.actor }}\n*Commit:* ${{ github.sha }}\n*Estado:* La compilación o las pruebas han fallado. Revisen los logs en GitHub Actions."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: 🔍 CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:java"

      - name: 📊 Sonar Analysis
        run: >
          mvn -B sonar:sonar 
          -Dsonar.projectKey=zuribehobide_${{ env.ARTIFACT }}
          -Dsonar.organization=zuribehobide 
          -Dsonar.host.url=https://sonarcloud.io 
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
